// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package com.resume.user.v1;

public interface GenericResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resume.user.v1.GenericResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1 [json_name = "status"];</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1 [json_name = "status"];</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2 [json_name = "message"];</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
