// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package com.resume.user.v1;

public interface GetMeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resume.user.v1.GetMeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Id = 1 [json_name = "Id"];</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string Id = 1 [json_name = "Id"];</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
