// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package com.resume.user.v1;

public interface SignUpUserInputOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resume.user.v1.SignUpUserInput)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string email = 2 [json_name = "email"];</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 2 [json_name = "email"];</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string password = 3 [json_name = "password"];</code>
   * @return The password.
   */
  java.lang.String getPassword();
  /**
   * <code>string password = 3 [json_name = "password"];</code>
   * @return The bytes for password.
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>string passwordConfirm = 4 [json_name = "passwordConfirm"];</code>
   * @return The passwordConfirm.
   */
  java.lang.String getPasswordConfirm();
  /**
   * <code>string passwordConfirm = 4 [json_name = "passwordConfirm"];</code>
   * @return The bytes for passwordConfirm.
   */
  com.google.protobuf.ByteString
      getPasswordConfirmBytes();
}
