// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package com.resume.user.v1;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_User_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_User_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_UserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_UserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_GenericResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_GenericResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_SignUpUserInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_SignUpUserInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_SignUpUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_SignUpUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_SignInUserInput_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_SignInUserInput_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_SignInUserResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_SignInUserResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_VerifyEmailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_VerifyEmailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_resume_user_v1_GetMeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_resume_user_v1_GetMeRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022user/v1/user.proto\022\016resume.user.v1\032\037go" +
      "ogle/protobuf/timestamp.proto\032\034google/ap" +
      "i/annotations.proto\"\323\001\n\004User\022\016\n\002id\030\001 \001(\t" +
      "R\002id\022\022\n\004name\030\002 \001(\tR\004name\022\024\n\005email\030\003 \001(\tR" +
      "\005email\0229\n\ncreated_at\030\004 \001(\0132\032.google.prot" +
      "obuf.TimestampR\tcreatedAt\0229\n\nupdated_at\030" +
      "\005 \001(\0132\032.google.protobuf.TimestampR\tupdat" +
      "edAt\"\033\n\004role\022\010\n\004user\020\000\022\t\n\005admin\020\001\"8\n\014Use" +
      "rResponse\022(\n\004user\030\001 \001(\0132\024.resume.user.v1" +
      ".UserR\004user\"C\n\017GenericResponse\022\026\n\006status" +
      "\030\001 \001(\tR\006status\022\030\n\007message\030\002 \001(\tR\007message" +
      "\"\201\001\n\017SignUpUserInput\022\022\n\004name\030\001 \001(\tR\004name" +
      "\022\024\n\005email\030\002 \001(\tR\005email\022\032\n\010password\030\003 \001(\t" +
      "R\010password\022(\n\017passwordConfirm\030\004 \001(\tR\017pas" +
      "swordConfirm\">\n\022SignUpUserResponse\022(\n\004us" +
      "er\030\001 \001(\0132\024.resume.user.v1.UserR\004user\"C\n\017" +
      "SignInUserInput\022\024\n\005email\030\001 \001(\tR\005email\022\032\n" +
      "\010password\030\002 \001(\tR\010password\"t\n\022SignInUserR" +
      "esponse\022\026\n\006status\030\001 \001(\tR\006status\022!\n\014acces" +
      "s_token\030\002 \001(\tR\013accessToken\022#\n\rrefresh_to" +
      "ken\030\003 \001(\tR\014refreshToken\"@\n\022VerifyEmailRe" +
      "quest\022*\n\020verificationCode\030\001 \001(\tR\020verific" +
      "ationCode\"\036\n\014GetMeRequest\022\016\n\002Id\030\001 \001(\tR\002I" +
      "d2\320\002\n\013UserService\022i\n\nSignUpUser\022\037.resume" +
      ".user.v1.SignUpUserInput\032\037.resume.user.v" +
      "1.GenericResponse\"\031\202\323\344\223\002\023:\001*\"\016/api/v1/si" +
      "gnup\022l\n\nSignInUser\022\037.resume.user.v1.Sign" +
      "InUserInput\032\".resume.user.v1.SignInUserR" +
      "esponse\"\031\202\323\344\223\002\023:\001*\"\016/api/v1/signin\022h\n\005Ge" +
      "tMe\022\034.resume.user.v1.GetMeRequest\032\034.resu" +
      "me.user.v1.UserResponse\"#\202\323\344\223\002\035:\001*Z\014\022\n/a" +
      "pi/v1/me\"\n/api/v1/meB\264\001\n\022com.resume.user" +
      ".v1B\tUserProtoP\001Z9github.com/leondevpt/r" +
      "esume-backend/apigen/user/v1;userv1\242\002\003RU" +
      "X\252\002\016Resume.User.V1\312\002\016Resume\\User\\V1\342\002\032Re" +
      "sume\\User\\V1\\GPBMetadata\352\002\020Resume::User:" +
      ":V1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
          com.google.api.AnnotationsProto.getDescriptor(),
        });
    internal_static_resume_user_v1_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_resume_user_v1_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_User_descriptor,
        new java.lang.String[] { "Id", "Name", "Email", "CreatedAt", "UpdatedAt", });
    internal_static_resume_user_v1_UserResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_resume_user_v1_UserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_UserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_resume_user_v1_GenericResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_resume_user_v1_GenericResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_GenericResponse_descriptor,
        new java.lang.String[] { "Status", "Message", });
    internal_static_resume_user_v1_SignUpUserInput_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_resume_user_v1_SignUpUserInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_SignUpUserInput_descriptor,
        new java.lang.String[] { "Name", "Email", "Password", "PasswordConfirm", });
    internal_static_resume_user_v1_SignUpUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_resume_user_v1_SignUpUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_SignUpUserResponse_descriptor,
        new java.lang.String[] { "User", });
    internal_static_resume_user_v1_SignInUserInput_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_resume_user_v1_SignInUserInput_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_SignInUserInput_descriptor,
        new java.lang.String[] { "Email", "Password", });
    internal_static_resume_user_v1_SignInUserResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_resume_user_v1_SignInUserResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_SignInUserResponse_descriptor,
        new java.lang.String[] { "Status", "AccessToken", "RefreshToken", });
    internal_static_resume_user_v1_VerifyEmailRequest_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_resume_user_v1_VerifyEmailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_VerifyEmailRequest_descriptor,
        new java.lang.String[] { "VerificationCode", });
    internal_static_resume_user_v1_GetMeRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_resume_user_v1_GetMeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_resume_user_v1_GetMeRequest_descriptor,
        new java.lang.String[] { "Id", });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.protobuf.TimestampProto.getDescriptor();
    com.google.api.AnnotationsProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
