// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package com.resume.user.v1;

public interface UserResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resume.user.v1.UserResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.resume.user.v1.User user = 1 [json_name = "user"];</code>
   * @return Whether the user field is set.
   */
  boolean hasUser();
  /**
   * <code>.resume.user.v1.User user = 1 [json_name = "user"];</code>
   * @return The user.
   */
  com.resume.user.v1.User getUser();
  /**
   * <code>.resume.user.v1.User user = 1 [json_name = "user"];</code>
   */
  com.resume.user.v1.UserOrBuilder getUserOrBuilder();
}
