// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package com.resume.user.v1;

/**
 * Protobuf type {@code resume.user.v1.VerifyEmailRequest}
 */
public final class VerifyEmailRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:resume.user.v1.VerifyEmailRequest)
    VerifyEmailRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use VerifyEmailRequest.newBuilder() to construct.
  private VerifyEmailRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VerifyEmailRequest() {
    verificationCode_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new VerifyEmailRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.resume.user.v1.UserProto.internal_static_resume_user_v1_VerifyEmailRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.resume.user.v1.UserProto.internal_static_resume_user_v1_VerifyEmailRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.resume.user.v1.VerifyEmailRequest.class, com.resume.user.v1.VerifyEmailRequest.Builder.class);
  }

  public static final int VERIFICATIONCODE_FIELD_NUMBER = 1;
  private volatile java.lang.Object verificationCode_;
  /**
   * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
   * @return The verificationCode.
   */
  @java.lang.Override
  public java.lang.String getVerificationCode() {
    java.lang.Object ref = verificationCode_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      verificationCode_ = s;
      return s;
    }
  }
  /**
   * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
   * @return The bytes for verificationCode.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getVerificationCodeBytes() {
    java.lang.Object ref = verificationCode_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      verificationCode_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(verificationCode_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, verificationCode_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(verificationCode_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, verificationCode_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.resume.user.v1.VerifyEmailRequest)) {
      return super.equals(obj);
    }
    com.resume.user.v1.VerifyEmailRequest other = (com.resume.user.v1.VerifyEmailRequest) obj;

    if (!getVerificationCode()
        .equals(other.getVerificationCode())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + VERIFICATIONCODE_FIELD_NUMBER;
    hash = (53 * hash) + getVerificationCode().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.resume.user.v1.VerifyEmailRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.resume.user.v1.VerifyEmailRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code resume.user.v1.VerifyEmailRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:resume.user.v1.VerifyEmailRequest)
      com.resume.user.v1.VerifyEmailRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.resume.user.v1.UserProto.internal_static_resume_user_v1_VerifyEmailRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.resume.user.v1.UserProto.internal_static_resume_user_v1_VerifyEmailRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.resume.user.v1.VerifyEmailRequest.class, com.resume.user.v1.VerifyEmailRequest.Builder.class);
    }

    // Construct using com.resume.user.v1.VerifyEmailRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      verificationCode_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.resume.user.v1.UserProto.internal_static_resume_user_v1_VerifyEmailRequest_descriptor;
    }

    @java.lang.Override
    public com.resume.user.v1.VerifyEmailRequest getDefaultInstanceForType() {
      return com.resume.user.v1.VerifyEmailRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.resume.user.v1.VerifyEmailRequest build() {
      com.resume.user.v1.VerifyEmailRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.resume.user.v1.VerifyEmailRequest buildPartial() {
      com.resume.user.v1.VerifyEmailRequest result = new com.resume.user.v1.VerifyEmailRequest(this);
      result.verificationCode_ = verificationCode_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.resume.user.v1.VerifyEmailRequest) {
        return mergeFrom((com.resume.user.v1.VerifyEmailRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.resume.user.v1.VerifyEmailRequest other) {
      if (other == com.resume.user.v1.VerifyEmailRequest.getDefaultInstance()) return this;
      if (!other.getVerificationCode().isEmpty()) {
        verificationCode_ = other.verificationCode_;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              verificationCode_ = input.readStringRequireUtf8();

              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }

    private java.lang.Object verificationCode_ = "";
    /**
     * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
     * @return The verificationCode.
     */
    public java.lang.String getVerificationCode() {
      java.lang.Object ref = verificationCode_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        verificationCode_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
     * @return The bytes for verificationCode.
     */
    public com.google.protobuf.ByteString
        getVerificationCodeBytes() {
      java.lang.Object ref = verificationCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        verificationCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
     * @param value The verificationCode to set.
     * @return This builder for chaining.
     */
    public Builder setVerificationCode(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      verificationCode_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
     * @return This builder for chaining.
     */
    public Builder clearVerificationCode() {
      
      verificationCode_ = getDefaultInstance().getVerificationCode();
      onChanged();
      return this;
    }
    /**
     * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
     * @param value The bytes for verificationCode to set.
     * @return This builder for chaining.
     */
    public Builder setVerificationCodeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      verificationCode_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:resume.user.v1.VerifyEmailRequest)
  }

  // @@protoc_insertion_point(class_scope:resume.user.v1.VerifyEmailRequest)
  private static final com.resume.user.v1.VerifyEmailRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.resume.user.v1.VerifyEmailRequest();
  }

  public static com.resume.user.v1.VerifyEmailRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VerifyEmailRequest>
      PARSER = new com.google.protobuf.AbstractParser<VerifyEmailRequest>() {
    @java.lang.Override
    public VerifyEmailRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VerifyEmailRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VerifyEmailRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.resume.user.v1.VerifyEmailRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

