// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user/v1/user.proto

package com.resume.user.v1;

public interface VerifyEmailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:resume.user.v1.VerifyEmailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
   * @return The verificationCode.
   */
  java.lang.String getVerificationCode();
  /**
   * <code>string verificationCode = 1 [json_name = "verificationCode"];</code>
   * @return The bytes for verificationCode.
   */
  com.google.protobuf.ByteString
      getVerificationCodeBytes();
}
