// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"github.com/leondevpt/resume-backend/internal/app"
	"github.com/leondevpt/resume-backend/internal/biz"
	"github.com/leondevpt/resume-backend/internal/config"
	"github.com/leondevpt/resume-backend/internal/server"
	"github.com/leondevpt/resume-backend/internal/service"
)

// Injectors from wire.go:

func wireApp(c context.Context, cfg *config.Config) (*app.App, error) {
	userUseCase := biz.NewUserUseCase()
	userServiceServer := service.NewUserService(userUseCase)
	grpcServer := server.NewGrpcServer(c, cfg, userServiceServer)
	appApp := app.NewApp(cfg, grpcServer)
	return appApp, nil
}
